### ISSUE TITLE
Running build on release mode panics

### ISSUE THREAD

**Issue by Lauel09** [dskart/rustcraft#2]
Hi 
So, First I git cloned the project,checked the dependencies and ran it with the command  `cargo run --release -- -c` .
Here is the output,
```bash
sol@solmate:~/Documents/projects/rustcraft$ cargo run --release -- -c
    Finished release [optimized] target(s) in 6.51s
     Running `target/release/rustcraft -c`
May 07 10:15:34.941 INFO Generating World...
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
      note: label = `Vertex Buffer`
    not enough memory left


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
```
Which traces back to , 
```rust
fn default_error_handler(err: crate::Error) {
    eprintln!("wgpu error: {}\n", err);

    panic!("Handling wgpu errors as fatal by default");
}
```
and goes back to , 
```rust 
pub enum Error {
    /// Out of memory error
    OutOfMemoryError {
        ///
        source: Box<dyn error::Error + Send + Sync + 'static>,
    }, 
    ...
```
I am a Rust beginner ,and there is one thing I am not able to understand here is that if this program is panicking and is going through the usual process of unwinding then why is it seg faulting here ?

**Comment by dskart** [comment]
Hey! It looks like you did nothing wrong! But from what I can see from your error, it looks like your gpu does not have enough memory to load the vertex buffer.

I have have not tested this on different devices and it is not the most optimized code, so it could just be your gpu does not have a enough memory.


If you go in the `world.rs` file, you should see a `WORLD_SIZE` constant, if you change that to a smaller number, it will reduce the buffer size that is being loaded (but the area rendered around you will be smaller). Let me know if this works, if not I don't think I can really fix the buffer size problem without a big redesign.

**Comment by dskart** [comment]
Also the reason why it is segfaulting is because it's the wgpu crate that is panicking, the wgpu crate probably uses a bunch of unsafe rust to talk to your gpu which can definitely segfault.

**Comment by Lauel09** [comment]
Oh thanks,I just noticed that I had changed my settings to Intel Mode, as you suggested I reduced the `WORLD_SIZE` constant by half(to 5), I am getting ,

```bash 
sol@solmate:~/Documents/projects/rustcraft$ cargo run --release -- -c
   Compiling rustcraft v0.1.0 (/home/sol/Documents/projects/rustcraft)
    Finished release [optimized] target(s) in 15.79s
     Running `target/release/rustcraft -c`
May 07 19:29:00.628 INFO Generating World...
May 07 19:29:01.364 INFO World Generated!
May 07 19:29:02.487 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:03.488 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:04.488 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:05.488 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:06.489 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:07.489 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:08.490 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:09.491 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:10.491 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:11.491 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:12.492 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:13.492 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:14.492 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:15.493 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:16.493 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:17.493 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:18.494 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:19.494 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:20.495 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:21.495 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:22.495 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:23.496 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:24.496 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:25.496 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:26.497 ERRO A timeout was encountered while trying to acquire the next frame
May 07 19:29:27.497 ERRO A timeout was encountered while trying to acquire the next frame
```
and goes on.Looking at the RAM usage ,which reduced to 4 gigs rather than reaching and 8 and seg faulting.Even if I look at RUST_BACKTRACE=full,I am not able to actually trace it back like where exactly the error is being generated from ?
```rust
May 07 19:34:26.709 ERRO A timeout was encountered while trying to acquire the next frame

Stack backtrace:
   0: rustcraft::renderer::Renderer::render
   1: rustcraft::event_loop::{{closure}}
   2: winit::platform_impl::platform::x11::EventLoop<T>::run
   3: winit::platform_impl::platform::EventLoop<T>::run
   4: winit::event_loop::EventLoop<T>::run
   5: rustcraft::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/6b5de7aaec2955f2c7c7c82521a9186f2ba4f037/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/6b5de7aaec2955f2c7c7c82521a9186f2ba4f037/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/6b5de7aaec2955f2c7c7c82521a9186f2ba4f037/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/6b5de7aaec2955f2c7c7c82521a9186f2ba4f037/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/6b5de7aaec2955f2c7c7c82521a9186f2ba4f037/library/std/src/rt.rs:34:21
   9: main
  10: __libc_start_main
  11: _start
```
Also,thank you for your time. I have no prior experience with wgpu and didn't really understood "how-exactly" can I use it until I saw your project.

**Comment by dskart** [comment]
Umm, I am not sure exactly what is lagging here, the next frame problem points me toward a `winit` problem (the crate I am using to create a window and "frames"). Doing a stack backtrace on this won't give you too much information I think as it looks less like an error with the code itself, and more something to do with the lack of memory or wgpu/winit not being able to communicate with your hardware well for some reason. 

This project is definitely intended just to be used as a fun project so it is bound to break on some devices. Let me know if you find any solution to the problem!

I recommend maybe going over this: [learning wgpu](https://sotrh.github.io/learn-wgpu/). If this tutorial works on your hardware then it might be something to do with my side of the code. (this is also a great tutorial about wgpu and gpu programming!)

**Comment by Lauel09** [comment]
Oh that explains it.Thank you for making your project open source,I am closing the issue.
